apps/core/templates/login.html, pyjobs/settings.py, pyjobs/templates/modal-login.html, pyjobs/templates/registration/password_reset_complete.html, pyjobs/templates/registration/password_reset_confirm.html, pyjobs/templates/registration/password_reset_done.html, pyjobs/templates/registration/password_reset_email.html, pyjobs/templates/registration/password_reset_form.html, pyjobs/templates/registration/password_reset_subject.txt, pyjobs/urls.py
=> Organizado INSTALLED_APPS

apps/jobs/admin.py, apps/jobs/filters.py, apps/jobs/models.py, apps/jobs/views.py, pyjobs/templates/base.html, pyjobs/templates/jobs.html, requirements-dev.txt, requirements.txt
Filtro de vagas adicionado ao PyJobs!
=> Filtro de vagas adicionado

pyjobs/api/resources.py, pyjobs/core/models.py, pyjobs/core/utils.py, pyjobs/pyjobs/settings.py, pyjobs/pyjobs/urls.py, requirements.txt
Now we have the capability of sending new job offers automatically to our facebook page!
=> Facebook API merged into PyJobs Source code

pyjobs/core/models.py, pyjobs/core/templates/index.html, pyjobs/core/views.py
Implementada a pesquisa por vagas.
Criado um campo input text onde o usuário do PyJobs poderia digitar o que deseja pesquisar.
Busca por palavras/frases completas... hoje não foi feito um split dos termos digitados para pesquisar por múltiplas alternativas.
Ex: São Paulo
Encontra somente as ocorrências onde "São Paulo" foi definido, não procurando por ocorrências de São e/ou Paulo também.
Busca nos seguintes campos usando o icontains do Django:
- Título
- Local
- Descrição
- Requisitos
=> Pesquisa de vagas : issue #67

README.md
=> Updating  README

pyjobs/core/urls.py, pyjobs/pyjobs/urls.py
fiz uma pequena refatoração no urls para melhorar um pouco a estrutura do projeto.
=> create refactoring in urls

Procfile, docker-compose.yml, pyjobs/core/models.py, pyjobs/core/tests/test_job_model.py, pyjobs/core/tests/test_job_views.py, pyjobs/settings.py
Olá a todos, agora (com a maravilhosa e bem-vinda) ajuda do @cuducos (Ahoy), temos o docker-compose rodando com os arquivos de `.env` e o circle-ci rodando em nossa stack.
Agora só nos resta acertar os testes do PyJobs para podermos iniciar a migração para o Django 2.1
=> Docker-compose e Circle-CI rodando tranquilamente

.coveragerc, .travis.yml, README.md
Esse pull request adiciona a cobertura de testes ao fluxo de integração contínua. Para o `README.md` ficar mais visualmente mais uniforme, sugeri usarmos sempre os badges de um mesmo serviço (shields.io no caso).
=> Adiciona cobertura de testes à integração contínua

pyjobs/core/models.py, pyjobs/core/tests/test_job_model.py
Como explicado nas mensagens de cada _commit_ ; )
=> Refatoramentos de menor importância

pyjobs/core/tests/test_job_views.py, pyjobs/core/urls.py, pyjobs/core/views.py
Este feed irá auxiliar na automatização de newsletters do PyJobs! Este feed servirá como fonte para disparo de mensagem a cada nova vaga destacada e para o resumo semanal de vagas destacadas.
=> Adiciona feed de jobs premium

pyjobs/core/management/commands/send_weekly_summary.py
Agora existe uma command line para enviar o resumo semanal do PyJobs automaticamente.
=> Envio de resumo semanal pelo Telegram pelo Heroku

pyjobs/core/admin.py, pyjobs/core/management/commands/send_feedback_request.py, pyjobs/core/managers.py, pyjobs/core/models.py, pyjobs/core/tests/test_job_model.py, pyjobs/core/views.py
This branch enables admins that runs PyJobs to collect feedback automatically
=> Feedback collection

pyjobs/core/templates/job_details.html, pyjobs/core/tests/test_job_views.py
As [asked](https://twitter.com/vmesel/status/1131566512823767041).
=> Better translate verb "to apply"

pyjobs/core/context_processors.py, pyjobs/core/templates/base.html, pyjobs/settings.py
- Google Analytics tag shouldn't be on the project code, it should be one of the environment vars.
=> Externalize Google Analytics code

pyjobs/core/templates/login.html
Adds new help text to the template and new error messages.
=> Fix login template with new help text

.coveragerc, pyjobs/core/tests/test_apps.py, pyjobs/core/tests/test_job_views.py
Add more tests coverage and remove unnecessary management commands on `.coveragerc`
=> Add some more tests

pyjobs/core/managers.py, pyjobs/core/models.py
For less complexity, we reduced two functions added from few commits before. The function enables users to filter for `premium jobs`.
=> Refactor the code for DRY

pyjobs/core/tests/test_newsletter.py
Co-authored-by: Cuducos <cuducos@users.noreply.github.com>
=> Add mailchimp3 mock correctly

pyjobs/core/forms.py
Esse pull request atualiza o placeholder dos campos pra deixar mais intuitivo e ocupar menos espaço na tela do usuário
=> #173 - Better field placeholders

pyjobs/core/forms.py, pyjobs/core/tests/test_job_views.py, pyjobs/core/views.py
A migração da validação do recaptcha para o forms.py permite com que façamos a modularização melhor do sistema.
Para isso, tiramos toda a lógica do recaptcha da view e colocamos no módulo `JobForm.is_valid()`
=> Migra a validação do recaptcha para o forms.py

Pipfile, Pipfile.lock, ROADMAP.md, pyjobs/core/forms.py, pyjobs/core/migrations/0025_rename_skill_model.py, pyjobs/core/tests/test_intranet_views.py, pyjobs/core/tests/test_job_model.py, pyjobs/core/views.py, pyjobs/marketing/models.py, pyjobs/urls.py
Atualizar PyJobs para Django 2.2.*
=> 188 atualizar para django2.2

pyjobs/core/models.py, pyjobs/core/templates/base.html, pyjobs/core/templates/index.html, pyjobs/core/templates/job_details.html, pyjobs/core/views.py
Esta PR fecha alguns problemas de layout menores que foram esquecidos de serem implementados durante a aplicação do novo layout.
=> Makes some fixes to layout

pyjobs/core/templates/job_details.html, pyjobs/core/templates/login.html
Esse PR melhora a usabilidade do site para usuários que estão acessando as vagas sem estarem logados no site, com essa melhoria o usuário será redirecionado de volta para página da vaga após a realização do login, evitando que o mesmo precise pesquisar pela vaga novamente.
=> Redirect para página da vaga após o login

pyjobs/core/filters.py, pyjobs/core/templates/index.html
- Adicionado filtro de pesquisa da vaga por regime de contratação
- Removido filtro de pesquisa de requisitos da vaga
close #242
=> add filter with contract regime

pyjobs/core/templates/services.html
Alteração do template "services.html" para exibir corretamente as variáveis, concatenando-as dentro do `{% translate..%}`.
=> Corrige template services.html
